SWP391_HealthCareProject/Controllers/CampaignController.cs
using Microsoft.AspNetCore.Mvc;
using SWP391_HealthCareProject.DataAccess;
using SWP391_HealthCareProject.Filters;
using SWP391_HealthCareProject.Models;
using SWP391_HealthCareProject.ViewModels;

namespace SWP391_HealthCareProject.Controllers
{
    public class CampaignController : Controller
    {

        public void LoadSession()
        {
            if (HttpContext.Session.GetObjectFromJson<User>("User") != null)
            {
                var userInfo = HttpContext.Session.GetObjectFromJson<User>("User");
                ViewBag.UserName = userInfo.UserName;
                ViewBag.UserId = userInfo.UserId;
                ViewBag.User = userInfo;
                ViewBag.Volunteer = VolunteerDAO.GetVolunteerByUserId(userInfo.UserId);
            }
        }

        [RequestAuthentication]
        public IActionResult Detail(int id)
        {
            LoadSession();
            var volunteerInfo = HttpContext.Session.GetObjectFromJson<Volunteer>("Volunteer");
            var cD = CampaignDAO.getCampaignById(id);
            var participate = ParticipateDAO.GetParticipate(volunteerInfo.VolunteerId, id);
            if(participate != null)
            {
                ViewBag.VolunteerId = participate.VolunteerId;
            }
            CampaignParticipationViewModel participateDetails = new CampaignParticipationViewModel()
            {
                Campaign = cD
            };
            return View(participateDetails);
        }


        [RequestAuthentication]
        public IActionResult Register(int id)
        {
            LoadSession();
            var locations = CampaignLocationDAO.GetLocationsByCampaignId(id);
            CampaignParticipationViewModel participateDetails = new CampaignParticipationViewModel();
            ViewBag.CampaignId = id;
            participateDetails.CampaignLocations = locations;
            return View(participateDetails);
        }

        public IActionResult ErrorCampaign()
        {
            LoadSession();
            return View();
        }
        public ActionResult ShowSearch(DateTime date, string location)
        {
            LoadSession();
            var model = CampaignDAO.searchCampaign(date, location);
            if (model.Count == 0) { return RedirectToAction("ErrorCampaign"); }
            else
            {
                return View(model);

            }
        }

        [RequestAuthentication]
        public IActionResult Appointment(CampaignParticipationViewModel participateDetails)
        {
            LoadSession();
            var cD = CampaignDAO.getCampaignById(participateDetails.Participate.CampaignId);
            var volunteer = HttpContext.Session.GetObjectFromJson<Volunteer>("Volunteer");
            participateDetails.Campaign = cD;
            participateDetails.Participate.VolunteerId = volunteer.VolunteerId;
            participateDetails.Participate.RegisteredDate = DateTime.Now;
            ParticipateDAO.AddParticipate(participateDetails.Participate);
            CampaignDAO.UpdateCampaign(participateDetails.Participate.CampaignId);
            ViewBag.Volunteer = volunteer;
            return View(participateDetails);
        }

        public IActionResult UnenrollCampaign(CampaignParticipationViewModel participateDetails)
        {
            LoadSession();
            ParticipateDAO.RemoveParticipate(participateDetails.Participate.VolunteerId, participateDetails.Campaign.CampaignId);
            CampaignDAO.ReduceVolunteerNumber(participateDetails.Campaign.CampaignId);
            var cD = CampaignDAO.getCampaignById(participateDetails.Campaign.CampaignId);
            participateDetails.Campaign = cD;
            return View("Detail", participateDetails);
        }


    }
}

SWP391_HealthCareProject/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SWP391_HealthCareProject.DataAccess;
using SWP391_HealthCareProject.Models;
using System.Diagnostics;
using SWP391_HealthCareProject.DataAccess;
using Microsoft.SqlServer.Management.Smo;
using NuGet.ContentModel;
using User = SWP391_HealthCareProject.Models.User;

namespace SWP391_HealthCareProject.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public void LoadSession()
        {
            if (HttpContext.Session.GetObjectFromJson<User>("User") != null)
            {
                var userInfo = HttpContext.Session.GetObjectFromJson<User>("User");
                VolunteerDAO volunteerDAO = new VolunteerDAO();
                var volunteer = VolunteerDAO.GetVolunteerByUserId(userInfo.UserId);
                ViewBag.UserName = userInfo.UserName;
                ViewBag.UserId = userInfo.UserId;
                ViewBag.User = userInfo;
                ViewBag.Volunteer = volunteer;
            }
        }

        public IActionResult Index()
        {
            LoadSession();
            PostDAO postDAO = new PostDAO();
            CampaignDAO campaignDAO = new CampaignDAO();    
            VolunteerDAO volunteerDAO = new VolunteerDAO();
            PlanDAO planDAO = new PlanDAO();


            List<Post> postList = new List<Post>();
            postList = postDAO.getAllPost();
            List<Campaign> campaignList = new List<Campaign>();
            campaignList = campaignDAO.getAllCampaign();
            List<Volunteer> volunteerList = new List<Volunteer>();
            volunteerList = volunteerDAO.getAllVolunteer();
            List<Plan> planplist = new List<Plan>();
            planplist = planDAO.getAllPlan();

            List<User> userList = VolunteerDAO.getAllUser();
            HomeModels homeModels = new HomeModels();
            homeModels.PostViewModel = postList;
            homeModels.CampaignViewModel = campaignList; 
            homeModels.VolunteerViewModel = volunteerList;
            homeModels.PlanViewModel = planplist;
            homeModels.UserViewModel = userList;
            return View(homeModels);
        }
 
        public IActionResult Privacy()
        {

            return View();
        }

        public IActionResult CampaignList()
        {
            LoadSession();
            HomeModels homeModels = new HomeModels();
            return View(homeModels);
        }

        public IActionResult PostList()
        {
            LoadSession();
            var postDao = new PostDAO();
            var pD = postDao.getAllPost();
            return View(pD);
        }

        public IActionResult SearchCampaign()
        {
            LoadSession();
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        
    }
}

SWP391_HealthCareProject/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using SWP391_HealthCareProject.DataAccess;
using SWP391_HealthCareProject.Models;

namespace SWP391_HealthCareProject.Controllers
{
    public class PostController : Controller
    {
        public void LoadSession()
        {
            if (HttpContext.Session.GetObjectFromJson<User>("User") != null)
            {
                var userInfo = HttpContext.Session.GetObjectFromJson<User>("User");
                ViewBag.UserName = userInfo.UserName;
                ViewBag.UserId = userInfo.UserId;
                ViewBag.User = userInfo;
                ViewBag.Volunteer = VolunteerDAO.GetVolunteerByUserId(userInfo.UserId);
            }
        }

        public IActionResult Index(int id)
        {
            LoadSession();
            var pD = new PostDAO();
            var p = pD.getPostById(id);
            return View(p);
        }
       
       
    }
}

SWP391_HealthCareProject/Views/Home/CampaignList.cshtml
@using SWP391_HealthCareProject.DataAccess;
@model HomeModels
@{
    ViewBag.Title = "Campaign List";
    Layout = "_Layout";
}

<div class="banner">
    <div class="h-100 layer">
        <div class="row h-100 align-items-center">
            <div class="col-12 text-center">
                <h1 class="header-text">Donation Campaign</h1>
                <a href="/Home/PostList" type="button" class="btn btn-outline-light mx-lg-3 mx-md-3 mx-sm-3 mx-3 my-3 btn-readmore">
                    Read More
                </a>
            </div>
        </div>
    </div>
</div>




<section class="py-5" id="content">
    <div class="container">
        <!-- First 3 cards -->
        <div class="row ">
            @foreach (var item in Model.getAllCampaign())
            {
                if (item.Status)
                {
                    <div class="col-lg-4 col-md-6 d-flex justify-content-center">
                        <div class="card " style="width: 18rem;">
                            @if (@Model.GetPostByCampaignId(item.CampaignId) != null)
                            {
                                <img class="card-img-top"
                         src="@Model.GetPostByCampaignId(item.CampaignId).Img"
                         alt="Card image cap">
                            }
                            <div class="card-body">
                                <div class="d-flex justify-content-between">
                                    <span><i class="fa-regular fa-calendar"></i> @item.StartDate.ToString("dd/MM/yyyy")</span>
                                    <span><i class="fa-solid fa-location-dot"></i> @item.Province</span>
                                </div>
                                <h1 class="card-title">@item.Name</h1>
                                <p class="card-text">
                                    @if (@Model.GetPostByCampaignId(item.CampaignId) != null)
                                    {
                                        @Model.GetPostByCampaignId(item.CampaignId).Description
                                    }
                                </p>
                            </div>
                            <div class="container mb-3">
                                <a>@Html.ActionLink("Read More","Detail","Campaign",new {id=item.CampaignId}, new {@style = "color: #EE2E2E;"})</a>
                            </div>
                        </div>
                    </div>
                }

            }
        </div>
    </div>
</section>

SWP391_HealthCareProject/Views/Home/Index.cshtml
@using SWP391_HealthCareProject.DataAccess;
@model HomeModels
@{
    ViewBag.Title = "Home Page";
    Layout = "_Layout";
}

@{
    if (ViewBag.User != null)
    {
        Volunteer currentVolunteer = Model.GetVolunteerByUserId(ViewBag.UserId);
        if (currentVolunteer.FirstName == null)
        {
            <script type="text/javascript">
                window.onload = function () {
                    notifyMe()
                };
            </script>
        }
    }
}


<!-- Header Image -->
<header class="masthead">
    <div class="container h-100">
        <div class="row h-100 align-items-center">
            <div class="col-12 text-center">
                <h1 class="header-text">Blood Donor</h1>
                <p class="lead">
                    A website for blood donor, we will have you find a campaign more easily!
                    If you’re a blood donor, you’re a hero to someone, somewhere, who received your gracious gift of life.
                </p>
                <a href="/Home/CampaignList" type="button" class="btn btn-lg btn-join ">Join Now</a>
                <a href="/Home/PostList" type="button" class="btn btn-outline-light mx-lg-3 mx-md-3 mx-sm-3 mx-3 my-3 btn-readmore">
                    Read More
                </a>

            </div>

        </div>

    </div>
</header>

<section class="py-5" id="content">

    <div class="container">
        <div class="row ">
            <div class="col-lg-4 col-md-6 d-flex justify-content-center">
                @{
                    Post post1 = Model.GetPostById(1);

                    <div class="card " style="width: 18rem;">
                        <img class="card-img-top"
                             src="@post1.Img">
                        <div class="card-body">
                            <h1 class="card-title">@post1.Title</h1>
                            <p class="card-text">
                                @post1.Description
                            </p>
                        </div>
                        <div class="container mb-4">
                            <a>@Html.ActionLink("Read More","Index","Post", new {id=post1.PostId})</a>
                        </div>
                    </div>

                }
            </div>
            <div class="col-lg-4 col-md-6 d-flex justify-content-center">
                @{
                    Post post2 = Model.GetPostById(2);

                    <div class="card " style="width: 18rem;">
                        <img class="card-img-top"
                             src="@post2.Img">
                        <div class="card-body">
                            <h1 class="card-title">@post2.Title</h1>
                            <p class="card-text">
                                @post2.Description
                            </p>
                        </div>
                        <div class="container mb-4">
                            <a>@Html.ActionLink("Read More","Index","Post", new {id=post2.PostId})</a>
                        </div>
                    </div>

                }
            </div>
            <div class="col-lg-4 col-md-6 d-flex justify-content-center">
                @{
                    Post post3 = Model.GetPostById(3);

                    <div class="card " style="width: 18rem;">
                        <img class="card-img-top"
                             src="@post3.Img">
                        <div class="card-body">
                            <h1 class="card-title">@post3.Title</h1>
                            <p class="card-text">
                                @post3.Description
                            </p>
                        </div>
                        <div class="container mb-4">

                            <a>@Html.ActionLink("Read More","Index","Post", new {id=post3.PostId})</a>
                        </div>
                    </div>

                }
            </div>
        </div>


        <div class="row py-4 " style="box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);">
            @{
                Post post4 = Model.GetPostById(3);
                <div class="col-lg-7 d-flex justify-content-center">
                    <img src="@post4.Img"
                         class="img-responsive " style="width: 40rem;height: 20rem;object-fit: cover;">
                </div>
                <div class="col-lg-5 big-card ">
                    <h1 class="py-4">@post4.Title</h1>
                    <p class="card-text">
                        @post4.Description
                    </p>
                    @Html.ActionLink("Read More","Index","Post", new {id=post4.PostId}, new { @class = "btn btn-lg btn-join mt-4" })
                </div>
            }
        </div>

    </div>

</section>
<section id="carousel">
    <div id="campaigncarousel" class="carousel slide" data-ride="false">
        <div class="carousel-inner">
            @{
                Campaign c = Model.GetCampaignById(1);
                Campaign c1 = Model.GetCampaignById(3);
                <div class="carousel-item active" style="background-color: #FF6262;">
                    <h2>
                        @c.Name.ToUpper()
                    </h2>
                    <img src="@post1.Img" class="img-responsive img-thumbnail">
                    <p>
                        Join this campaign right now. there are more than 124 volunteers have registerd!
                    </p>
                </div>
                <div class="carousel-item">
                    <h2>
                        @c1.Name.ToUpper()
                    </h2>
                    <img src="@post2.Img" class="img-responsive img-thumbnail">
                    <p>
                        Join this campaign right now. there are more than 124 volunteers have registerd!
                    </p>
                </div>
            }
            <a class="carousel-control-prev" href="#campaigncarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#campaigncarousel" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>

        </div>
    </div>

</section>



<section id="top-volunteer" class="">
    <h1>Top Volunteers</h1>
    <hr width="150px" />
    <div class="row">
        @{
            Volunteer v1 = Model.GetVolunteerById(10);
            User u1 = Model.GetUserById(v1.UserId);
            <div class="col-md-4 volunteer d-flex justify-content-center">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="@u1.Avatar" alt="Card image cap">
                    <div class="card-body">
                        <p>Name: @v1.FirstName.ToUpper() @v1.LastName.ToUpper() </p>
                        <p>City: @v1.City</p>
                        <p>Date of birth: @v1.Dob.ToString("dd/MM/yyyy")</p>
                        <p>BloodType: @v1.BloodType</p>
                    </div>
                </div>
            </div>
        }
        @{
            Volunteer v2 = Model.GetVolunteerById(2);
            User u2 = Model.GetUserById(v2.UserId);
            <div class="col-md-4 volunteer d-flex justify-content-center">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="@u2.Avatar" alt="Card image cap">
                    <div class="card-body">
                        <p>Name: @v2.FirstName.ToUpper() @v2.LastName.ToUpper() </p>
                        <p>City: @v2.City</p>
                        <p>Date of birth: @v2.Dob.ToString("dd/MM/yyyy")</p>
                        <p>BloodType: @v2.BloodType</p>
                    </div>
                </div>
            </div>
        }
        @{
            Volunteer v3 = Model.GetVolunteerById(3);
            User u3 = Model.GetUserById(v3.UserId);
            <div class="col-md-4 volunteer d-flex justify-content-center">
                <div class="card" style="width: 18rem;">
                    <img class="card-img-top" src="@u3.Avatar" alt="Card image cap">
                    <div class="card-body">
                        <p>Name: @v3.FirstName.ToUpper() @v3.LastName.ToUpper() </p>
                        <p>City: @v3.City</p>
                        <p>Date of birth: @v3.Dob.ToString("dd/MM/yyyy")</p>
                        <p>BloodType: @v3.BloodType</p>
                    </div>
                </div>
            </div>
        }
    </div>


</section>

<section id="find-campaign">
    <div class="container">
        <h1>Find A Near By Campaign</h1>
        <hr width="150px" />
        <div class="row">
            <div class="col-md-6">
                <form method="" action="">
                    <input type="text" placeholder="First Name" required />
                    <input type="text" placeholder="Last Name" required />
                    <input type="text" placeholder="Email Address" required />
                    <input type="text" placeholder="City" required />
                    <textarea placeholder="Description" class="description"></textarea>
                    <a href="#" class="btn btn-join my-4 ml-3">Find Campaign</a>
                </form>
            </div>
            <div class="col-md-6">
                <img src="~/assets/findcp.png" />
            </div>
        </div>
    </div>
</section>



<script>
    //$(document).ready(function () {
    //    notifyMe();
    //});

    function createNotification() {

        var options = {
            body: 'Please go into your profile and fill in your details profile',
            icon: '/wwwroot/favicon.ico',
            dir: 'ltr'
        };

        var notification = new Notification("Hi there", options);

        notification.onclick = function () {
            window.open("https://localhost:7082/User/UserProfile");
        };
    }

    function notifyMe() {
        if (!("Notification" in window)) {
            alert("This browser does not support desktop notification");
        }
        else if (Notification.permission === "granted") {

            createNotification();

        }
        else if (Notification.permission !== 'denied') {
            Notification.requestPermission(function (permission) {
                if (!('permission' in Notification)) {
                    Notification.permission = permission;
                }
                if (permission === 'granted') {

                    createNotification();
                }
            });
        }
    }
</script>

SWP391_HealthCareProject/Views/Home/PostList.cshtml
@model List<SWP391_HealthCareProject.Models.Post>
@{
    ViewData["Title"] = "Post List";
    Layout = "_Layout";
}

<div class="banner">
    <div class="h-100 layer">
        <div class="row h-100 align-items-center">
            <div class="col-12 text-center">
                <h1 class="header-text">Post</h1>
            </div>
        </div>
    </div>
</div>



<section class="py-5" id="content">
    <div class="container">
        <!-- First 3 cards -->
        <div class="row ">
            @foreach (var item in Model)
            {
                <div class="col-lg-4 col-md-6 d-flex justify-content-center">
                    <div class="card " style="width: 18rem;">
                        <img class="card-img-top"
                         src="@item.Img"
                         alt="Card image cap">
                        <div class="card-body">
                            <h1 class="card-title">@item.Title</h1>
                            <p class="card-text">
                                @item.Description
                            </p>

                        </div>
                        <div class="card-footer">
                            <a>@Html.ActionLink("Read More","Index","Post", new {id=item.PostId})</a>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</section>

SWP391_HealthCareProject/Views/Home/SearchCampaign.cshtml
@page
@model SWP391_HealthCareProject.Controllers.SearchCampaignModel
@{
    ViewBag.Title = "Search Campaign";
    Layout = "_Layout";
}



<div class="container top">
    <h1 style="font-weight:600;font-size:3rem;">Time & Location</h1>
    <span style="font-family:'Segoe UI light'">Find campaigns!</span>
    @using(Html.BeginForm("ShowSearch","Campaign",FormMethod.Post))
    {
        <label for="">Date</label>
        <input type="date" class="form-control" name="date" required/>
        <label for="">Location</label>
        <input type="text" class="form-control" name="location" required/>
        <br/>
        <button type="submit" class="continue-btn my-5">Search</button>

    }
</div>